# AppVeyor configuration.

# For more details, see: https://www.appveyor.com/docs/lang/python/.
---
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- pip install tox

test_script:
- tox
